name: auto update gh-pages

on: [push]

jobs:
  tests-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploying the static website to gh-pages
        run: npm run deploy
